### PR TITLE
feat: add transaction support

### PR DESCRIPTION
**Pull request by achrinza**
~Blocked by #634~
Replaces #626

Signed-off by: Sergey Nosenko <darknos@gmail.com>
Signed-off-by: Rifa Achrinza <25147899+achrinza@users.noreply.github.com>

## Checklist

- [x] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [x] `npm test` passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](https://loopback.io/doc/en/contrib/style-guide-es6.html)
- [x] Commit messages are following our [guidelines](https://loopback.io/doc/en/contrib/git-commit-messages.html)

### CODE REVIEW

**Comment by marioestradarosa** [comment]
@darknos thanks for the PR and sorry for the inconvenience. Many developers are waiting for your new feature to be published 👍 .

**Comment by darknos** [comment]
any updates?

**Review by marioestradarosa — APPROVED** [review]

**Review by dhmlau — COMMENTED** [review]
I'm not familiar with the code but the changes look reasonable to me. 
As a nitpick, I wonder if we want to add some `debug` statement in there, like what we did in the postgresql connector. When debugging a transaction issue long time ago for that connector, it does help to have debug turned on and have something printed out. But this could be out of scope for this PR. Thanks.

**Comment by marioestradarosa** [comment]
> I wonder if we want to add some `debug` statement in there, like what we did in the postgresql connector.

The postgreSQL connector only print debug `isolation level, begin, rollback & commit` and those should be printed out from here instead [loopback-datasource-juggler](https://github.com/loopbackio/loopback-datasource-juggler/blob/master/lib/datasource.js) as a centralized location.

**Comment by achrinza** [comment]
@dhmlau I propose merging this PR first, then adding the debug statement later if needed.

**Comment by marioestradarosa** [comment]
> @dhmlau I propose merging this PR first, then adding the debug statement later if needed.

I believe that the debug print outs should be placed in the  loopback-datasource-juggler not on every connector. The reason why is because this debug printings are general and can be caught in the  loopback-datasource-juggler . We are duplicating code and effort.

**Review by dhmlau — APPROVED** [review]
Agreed to land this PR first and add the debug info as a separate PR. Thanks.

**Pull request merged**
